openapi: 3.0.2

info:
  title: California Flowers App
  description: BE API for the app products endpoint
  version: 1.0.0

servers:
  - url: https://wo1po3w8ud.execute-api.us-east-1.amazonaws.com/dev

paths:
  /products:
    get:
      summary: List of products
      description: List of products
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductList'
        500:
          description: "Internal server error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

  /products/{productId}:
    get:
      summary: Retrieve product by ID
      description: Retrieve product by ID
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        404:
          description: Product by ID was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

components:
  schemas:
    Product:
      type: object
      properties:
        title:
          type: string
          example: "Title"
        description:
          type: string
          example: "Some brief description"
        id:
          type: string
          example: "7567ec4b-b10c-48c5-9345-fc73c48a80a1"
        img:
          type: string
        count:
          type: integer
          format: int64
          example: 15
        price:
          type: integer
          format: int64
          example: 23.40
      required:
        - id
    ProductList:
      type: array
      items:
        $ref: '#/components/schemas/Product'
    NotFound:
      type: object
      properties:
        code:
          type: string
          example: 404
        message:
          type: string
          example: "Product with specified ID was not found!"
      required:
        - code
        - message
    InternalServerError:
      type: object
      properties:
        code:
          type: string
          example: 500
        message:
          type: string
          example: "Something went wrong"
      required:
        - code
        - message

